config/routes.rb
Rails.application.routes.draw do

  resources :bem_colaboradores
  get 'controle_alocacoes/index'
  get 'locacoes' => 'locacoes#index'
  get 'locacoes/materiais'
  get 'controle_alocacoes' => 'controle_alocacoes#index'
  get 'controle_alocacoes/itens'
  get 'bens/gera_patrimonio' => 'bens#gera_patrimonio'

  scope path_names: { new: 'novo', edit: 'editar' } do
    resources :material_locados
    resources :fornecedores
    resources :funcoes
    resources :prazo_locacoes
    resources :usuarios_mobiles
    resources :almoxarifes
    resources :bens
    resources :setores
    resources :centro_custos
    resources :colaboradores
    resources :posts
    resource  :funcao
    resources :materiais
    resources :insumos
    resources :grupo_insumos
    resources :estado_conservacoes

    namespace "admin" do
      resources :users do
        get 'redefinir_senha'
      end
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }, path_names: {sign_in: "login", sign_out: "logout"}
  as :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    delete "/logout" => "users/sessions#destroy"
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index", :as => :home

  get 'home' => "home#index"

  get "logout" => "users/sessions#new"

  TheRoleManagementPanel::Routes.mixin(self)
  patch '/admin/roles/:id/change' => 'admin/roles#change'

end

app/controllers/funcoes_controller.rb
class FuncoesController < ApplicationController
  before_action :set_funcao, only: [:show, :edit, :update, :destroy]

  # GET /funcoes
  # GET /funcoes.json
  def index
    @funcoes = Funcao.all.order(:descricao)
  end

  # GET /funcoes/1
  # GET /funcoes/1.json
  def show
  end

  # GET /funcoes/new
  def new
    @funcao = Funcao.new
  end

  # GET /funcoes/1/edit
  def edit
  end

  # POST /funcoes
  # POST /funcoes.json
  def create
    @funcao = Funcao.new(funcao_params)

    respond_to do |format|
      if @funcao.save
        format.html { redirect_to @funcao, notice: 'Funcao criada com sucesso.' }
        format.json { render :show, status: :created, location: @funcao }
      else
        format.html { render :new }
        format.json { render json: @funcao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcoes/1
  # PATCH/PUT /funcoes/1.json
  def update
    respond_to do |format|
      if @funcao.update(funcao_params)
        format.html { redirect_to @funcao, notice: 'Funcao atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @funcao }
      else
        format.html { render :edit }
        format.json { render json: @funcao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcoes/1
  # DELETE /funcoes/1.json
  def destroy
    @funcao.destroy
    respond_to do |format|
      format.html { redirect_to funcoes_url, notice: 'Funcao deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcao
      @funcao = Funcao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcao_params
      params.require(:funcao).permit(:descricao)
    end
end

app/helpers/funcoes_helper.rb
module FuncoesHelper
end

app/views/funcoes/_form.html.erb
<%= form_for(funcao, html: { class: 'form-horizontal' }) do |f| %>
  <%= render 'layouts/error_messages', model_name: funcao %>
  <div class="form-group">
    <%= f.label :descricao, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :descricao, :class => 'form-control',:required => true  %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to I18n.t('.cancel', default: I18n.t("helpers.links.cancel")),
                  funcoes_path, class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/funcoes/edit.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', :default => [:'helpers.titles.edit'], :model => @funcao.class.model_name.human) %></h3>
</div>
<%= render 'form', funcao: @funcao %>

app/views/funcoes/index.html.erb
<%- model_class = Funcao -%>
<div class="page-header" style="border: none">
  <h3><%=  I18n.t('activerecord.models.funcao') %></h3>
  <hr/>
  <%= link_to "Novo", new_funcao_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
       <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th width="10%">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @funcoes.each do |funcao| %>
      <tr>
        <td><%= funcao.descricao %></td>
        <td>
          <%= link_to  I18n.t('.edit', default: I18n.t("helpers.links.edit")), edit_funcao_path(funcao), class: 'btn btn-mini' %>
          <%= link_to I18n.t('.destroy', default: I18n.t("helpers.links.destroy")), funcao, method: :delete, data: { confirm:  I18n.t('.confirm', default:  I18n.t("helpers.links.confirm", default: 'Tem certeza?')) }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/funcoes/new.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: [:'helpers.titles.new'], model: @funcao.class.model_name.human) %></h3>
</div>
<%= render 'form', funcao: @funcao %>

app/views/funcoes/show.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: @funcao.class.model_name.human ) %></h3>
</div>
<dl class="dl-horizontal">
    <dt><strong>Descricao:</strong></dt>
  <dd><%= @funcao.descricao %></dd>
  </dl>
<div class="form-actions">
  <%= link_to I18n.t('.back', default: t("helpers.links.back")),
              funcoes_path, class: 'btn'  %>
  <%= link_to I18n.t('.edit', default: t("helpers.links.edit")),
              edit_funcao_path(@funcao), class: 'btn' %>
  <%= link_to I18n.t('.destroy', default: t("helpers.links.destroy")),
              funcao_path(@funcao),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Tem certeza que deseja remover o registro?')) },
              class: 'btn btn-danger' %>
</div>