config/routes.rb
Rails.application.routes.draw do

  resources :bem_colaboradores
  get 'controle_alocacoes/index'
  get 'locacoes' => 'locacoes#index'
  get 'locacoes/materiais'
  get 'controle_alocacoes' => 'controle_alocacoes#index'
  get 'controle_alocacoes/itens'
  get 'bens/gera_patrimonio' => 'bens#gera_patrimonio'

  scope path_names: { new: 'novo', edit: 'editar' } do
    resources :material_locados
    resources :fornecedores
    resources :funcoes
    resources :prazo_locacoes
    resources :usuarios_mobiles
    resources :almoxarifes
    resources :bens
    resources :setores
    resources :centro_custos
    resources :colaboradores
    resources :posts
    resource  :funcao
    resources :materiais
    resources :insumos
    resources :grupo_insumos
    resources :estado_conservacoes

    namespace "admin" do
      resources :users do
        get 'redefinir_senha'
      end
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }, path_names: {sign_in: "login", sign_out: "logout"}
  as :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    delete "/logout" => "users/sessions#destroy"
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index", :as => :home

  get 'home' => "home#index"

  get "logout" => "users/sessions#new"

  TheRoleManagementPanel::Routes.mixin(self)
  patch '/admin/roles/:id/change' => 'admin/roles#change'

end

app/models/usuarios_mobile.rb
class UsuariosMobile < ActiveRecord::Base
  belongs_to :colaborador
end

app/controllers/usuarios_mobiles_controller.rb
class UsuariosMobilesController < ApplicationController
  before_action :set_usuarios_mobile, only: [:show, :edit, :update, :destroy]

  # GET /usuarios_mobiles
  # GET /usuarios_mobiles.json
  def index
    @usuarios_mobiles = UsuariosMobile.all.order(:login)
  end

  # GET /usuarios_mobiles/1
  # GET /usuarios_mobiles/1.json
  def show
  end

  # GET /usuarios_mobiles/new
  def new
    @usuarios_mobile = UsuariosMobile.new
  end

  # GET /usuarios_mobiles/1/edit
  def edit
  end

  # POST /usuarios_mobiles
  # POST /usuarios_mobiles.json
  def create
    @usuarios_mobile = UsuariosMobile.new(usuarios_mobile_params)

    colaborador = Colaborador.find_by_id(params[:usuarios_mobile][:colaborador_id])

    @usuarios_mobile.colaborador = colaborador

    respond_to do |format|
      if @usuarios_mobile.save
        format.html { redirect_to @usuarios_mobile, notice: 'Usuarios mobile criado com sucesso.' }
        format.json { render :show, status: :created, location: @usuarios_mobile }
      else
        format.html { render :new }
        format.json { render json: @usuarios_mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios_mobiles/1
  # PATCH/PUT /usuarios_mobiles/1.json
  def update
    respond_to do |format|
      if @usuarios_mobile.update(usuarios_mobile_params)
        format.html { redirect_to @usuarios_mobile, notice: 'Usuarios mobile atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @usuarios_mobile }
      else
        format.html { render :edit }
        format.json { render json: @usuarios_mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios_mobiles/1
  # DELETE /usuarios_mobiles/1.json
  def destroy
    @usuarios_mobile.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_mobiles_url, notice: 'Usuarios mobile deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuarios_mobile
      @usuarios_mobile = UsuariosMobile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuarios_mobile_params
      params.require(:usuarios_mobile).permit(:login, :senha, :colaborador_id, :super_usuario)
    end
end

app/helpers/usuarios_mobiles_helper.rb
module UsuariosMobilesHelper
end

app/views/usuarios_mobiles/_form.html.erb
<%= form_for(usuarios_mobile, html: { class: 'form-horizontal' }) do |f| %>
  <%= render 'layouts/error_messages', model_name: usuarios_mobile %>
  <div class="form-group">
    <%= f.label :login, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :login, :class => 'form-control',:required => true  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :senha, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :senha, :class => 'form-control',:required => true  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :colaborador, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.select :colaborador_id, Colaborador.all().collect { |m| [m.nome, m.id ] }, {:prompt => 'Selecione'}, :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :super_usuario, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.select :super_usuario, [['Sim', true], ['Não', false]],:required => true  %>
    </div>
  </div>
 <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to I18n.t('.cancel', default: I18n.t("helpers.links.cancel")),
                  usuarios_mobiles_path, class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/usuarios_mobiles/edit.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', :default => [:'helpers.titles.edit'], :model => @usuarios_mobile.class.model_name.human) %></h3>
</div>
<%= render 'form', usuarios_mobile: @usuarios_mobile %>

app/views/usuarios_mobiles/index.html.erb
<%- model_class = UsuariosMobile -%>
<div class="page-header" style="border: none">
  <h3><%=  I18n.t('activerecord.models.usuarios_mobile') %></h3>
  <hr/>
  <%= link_to "Novo", new_usuarios_mobile_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
       <th><%= model_class.human_attribute_name(:login) %></th>
       <th><%= model_class.human_attribute_name(:senha) %></th>
       <th><%= model_class.human_attribute_name(:colaborador) %></th>
       <th><%= model_class.human_attribute_name(:super_usuario) %></th>
      <th width="10%">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios_mobiles.each do |usuarios_mobile| %>
      <tr>
        <td><%= usuarios_mobile.login %></td>
        <td><%= usuarios_mobile.senha %></td>
        <td><%= usuarios_mobile.colaborador.nome %></td>
        <td><%= usuarios_mobile.super_usuario %></td>
        <td>
          <%= link_to  I18n.t('.edit', default: I18n.t("helpers.links.edit")), edit_usuarios_mobile_path(usuarios_mobile), class: 'btn btn-mini' %>
          <%= link_to I18n.t('.destroy', default: I18n.t("helpers.links.destroy")), usuarios_mobile, method: :delete, data: { confirm:  I18n.t('.confirm', default:  I18n.t("helpers.links.confirm", default: 'Tem certeza?')) }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/usuarios_mobiles/new.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: [:'helpers.titles.new'], model: @usuarios_mobile.class.model_name.human) %></h3>
</div>
<%= render 'form', usuarios_mobile: @usuarios_mobile %>

app/views/usuarios_mobiles/show.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: @usuarios_mobile.class.model_name.human ) %></h3>
</div>
<dl class="dl-horizontal">
    <dt><strong>Login:</strong></dt>
  <dd><%= @usuarios_mobile.login %></dd>
    <dt><strong>Senha:</strong></dt>
  <dd><%= @usuarios_mobile.senha %></dd>
    <dt><strong>Colaborador:</strong></dt>
  <dd><%= @usuarios_mobile.colaborador.nome %></dd>
    <dt><strong>Super usuario:</strong></dt>
  <dd><%= @usuarios_mobile.super_usuario %></dd>
  </dl>
<div class="form-actions">
  <%= link_to I18n.t('.back', default: t("helpers.links.back")),
              usuarios_mobiles_path, class: 'btn'  %>
  <%= link_to I18n.t('.edit', default: t("helpers.links.edit")),
              edit_usuarios_mobile_path(@usuarios_mobile), class: 'btn' %>
  <%= link_to I18n.t('.destroy', default: t("helpers.links.destroy")),
              usuarios_mobile_path(@usuarios_mobile),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Tem certeza que deseja remover o registro?')) },
              class: 'btn btn-danger' %>
</div>