config/routes.rb
Rails.application.routes.draw do

  resources :bem_colaboradores
  get 'controle_alocacoes/index'
  get 'locacoes' => 'locacoes#index'
  get 'locacoes/materiais'
  get 'controle_alocacoes' => 'controle_alocacoes#index'
  get 'controle_alocacoes/itens'
  get 'bens/gera_patrimonio' => 'bens#gera_patrimonio'

  scope path_names: { new: 'novo', edit: 'editar' } do
    resources :material_locados
    resources :fornecedores
    resources :funcoes
    resources :prazo_locacoes
    resources :usuarios_mobiles
    resources :almoxarifes
    resources :bens
    resources :setores
    resources :centro_custos
    resources :colaboradores
    resources :posts
    resource  :funcao
    resources :materiais
    resources :insumos
    resources :grupo_insumos
    resources :estado_conservacoes

    namespace "admin" do
      resources :users do
        get 'redefinir_senha'
      end
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }, path_names: {sign_in: "login", sign_out: "logout"}
  as :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    delete "/logout" => "users/sessions#destroy"
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index", :as => :home

  get 'home' => "home#index"

  get "logout" => "users/sessions#new"

  TheRoleManagementPanel::Routes.mixin(self)
  patch '/admin/roles/:id/change' => 'admin/roles#change'

end

app/models/almoxarife.rb
class Almoxarife < ActiveRecord::Base
  belongs_to :colaborador
  belongs_to :centro_custo

  validates_presence_of :colaborador_id, :centro_custo_id
end

app/controllers/almoxarifes_controller.rb
class AlmoxarifesController < ApplicationController
  before_action :set_almoxarife, only: [:show, :edit, :update, :destroy]

  # GET /almoxarifes
  # GET /almoxarifes.json
  def index
    @almoxarifes = Almoxarife.all
  end

  # GET /almoxarifes/1
  # GET /almoxarifes/1.json
  def show
  end

  # GET /almoxarifes/new
  def new
    @almoxarife = Almoxarife.new
  end

  # GET /almoxarifes/1/edit
  def edit
  end

  # POST /almoxarifes
  # POST /almoxarifes.json
  def create
    @almoxarife = Almoxarife.new(almoxarife_params)

    respond_to do |format|
      if @almoxarife.save
        format.html { redirect_to @almoxarife, notice: 'Almoxarife criado com sucesso.' }
        format.json { render :show, status: :created, location: @almoxarife }
      else
        format.html { render :new }
        format.json { render json: @almoxarife.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /almoxarifes/1
  # PATCH/PUT /almoxarifes/1.json
  def update
    respond_to do |format|
      if @almoxarife.update(almoxarife_params)
        format.html { redirect_to @almoxarife, notice: 'Almoxarife atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @almoxarife }
      else
        format.html { render :edit }
        format.json { render json: @almoxarife.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almoxarifes/1
  # DELETE /almoxarifes/1.json
  def destroy
    @almoxarife.destroy
    respond_to do |format|
      format.html { redirect_to almoxarifes_url, notice: 'Almoxarife excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almoxarife
      @almoxarife = Almoxarife.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def almoxarife_params
      params.require(:almoxarife).permit(:colaborador_id, :centro_custo_id)
    end
end

app/helpers/almoxarifes_helper.rb
module AlmoxarifesHelper
end

app/views/almoxarifes/_form.html.erb
<%= form_for(almoxarife, html: { class: 'form-horizontal' }) do |f| %>
  <%= render 'layouts/error_messages', model_name: almoxarife %>
  <div class="form-group">
    <%= f.label :colaborador_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%#= f.text_field :colaborador, :class => 'form-control'  %>
      <%= f.select :colaborador_id, Colaborador.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :centro_custo_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%#= f.text_field :centro_custo, :class => 'form-control'  %>
      <%= f.select :centro_custo_id, CentroCusto.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to I18n.t('.cancel', default: I18n.t("helpers.links.cancel")),
                  almoxarifes_path, class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/almoxarifes/edit.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', :default => [:'helpers.titles.edit'], :model => @almoxarife.class.model_name.human) %></h3>
</div>
<%= render 'form', almoxarife: @almoxarife %>

app/views/almoxarifes/index.html.erb
<%- model_class = Almoxarife -%>
<div class="page-header" style="border: none">
  <h3><%=  I18n.t('activerecord.models.almoxarife') %></h3>
  <hr/>
  <%= link_to "Novo", new_almoxarife_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
       <th><%= model_class.human_attribute_name(:colaborador_id) %></th>
       <th><%= model_class.human_attribute_name(:centro_custo_id) %></th>
      <th width="10%">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @almoxarifes.each do |almoxarife| %>
      <tr>
        <td><%= almoxarife.colaborador %></td>
        <td><%= almoxarife.centro_custo %></td>
        <td>
          <%= link_to  I18n.t('.edit', default: I18n.t("helpers.links.edit")), edit_almoxarife_path(almoxarife), class: 'btn btn-mini' %>
          <%= link_to I18n.t('.destroy', default: I18n.t("helpers.links.destroy")), almoxarife, method: :delete, data: { confirm:  I18n.t('.confirm', default:  I18n.t("helpers.links.confirm", default: 'Tem certeza?')) }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/almoxarifes/new.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: [:'helpers.titles.new'], model: @almoxarife.class.model_name.human) %></h3>
</div>
<%= render 'form', almoxarife: @almoxarife %>

app/views/almoxarifes/show.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: @almoxarife.class.model_name.human ) %></h3>
</div>
<dl class="dl-horizontal">
    <dt><strong>Colaborador:</strong></dt>
  <dd><%= @almoxarife.colaborador %></dd>
    <dt><strong>Centro custo:</strong></dt>
  <dd><%= @almoxarife.centro_custo %></dd>
  </dl>
<div class="form-actions">
  <%= link_to I18n.t('.back', default: t("helpers.links.back")),
              almoxarifes_path, class: 'btn'  %>
  <%= link_to I18n.t('.edit', default: t("helpers.links.edit")),
              edit_almoxarife_path(@almoxarife), class: 'btn' %>
  <%= link_to I18n.t('.destroy', default: t("helpers.links.destroy")),
              almoxarife_path(@almoxarife),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Tem certeza que deseja remover o registro?')) },
              class: 'btn btn-danger' %>
</div>