config/routes.rb
Rails.application.routes.draw do

  resources :bem_colaboradores
  get 'controle_alocacoes/index'
  get 'locacoes' => 'locacoes#index'
  get 'locacoes/materiais'
  get 'controle_alocacoes' => 'controle_alocacoes#index'
  get 'controle_alocacoes/itens'
  get 'bens/gera_patrimonio' => 'bens#gera_patrimonio'

  scope path_names: { new: 'novo', edit: 'editar' } do
    resources :material_locados
    resources :fornecedores
    resources :funcoes
    resources :prazo_locacoes
    resources :usuarios_mobiles
    resources :almoxarifes
    resources :bens
    resources :setores
    resources :centro_custos
    resources :colaboradores
    resources :posts
    resource  :funcao
    resources :materiais
    resources :insumos
    resources :grupo_insumos
    resources :estado_conservacoes

    namespace "admin" do
      resources :users do
        get 'redefinir_senha'
      end
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }, path_names: {sign_in: "login", sign_out: "logout"}
  as :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    delete "/logout" => "users/sessions#destroy"
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index", :as => :home

  get 'home' => "home#index"

  get "logout" => "users/sessions#new"

  TheRoleManagementPanel::Routes.mixin(self)
  patch '/admin/roles/:id/change' => 'admin/roles#change'

end

app/controllers/bens_controller.rb
#encoding: utf-8
class BensController < ApplicationController
  before_action :set_bem, only: [:show, :edit, :update, :destroy]

  # GET /bens
  # GET /bens.json
  def index
    # @bens = Bem.all
    @bens_grid = initialize_grid(Bem, :include => [:situacao, :centro_custo, :setor, :tipo_bem],
        order: 'id',
        name: 'u1',
        :csv_file_name => "listagem_de_bens_#{Time.now.strftime('%d%m%y%H%M%S')}")
      export_grid_if_requested('u1' => 'grid') do
      end
  end

  # GET /bens/1
  # GET /bens/1.json
  def show
  end

  # GET /bens/new
  def new
    @bem = Bem.new
  end

  # GET /bens/1/edit
  def edit
  end

  # POST /bens
  # POST /bens.json
  def create
    @bem = Bem.new(bem_params)

    respond_to do |format|
      if @bem.save
        format.html { redirect_to bens_path, notice: t('messages.cadastro_sucesso', :model => "Item") }
        format.json { render :show, status: :created, location: @bem }
      else
        format.html { render :new }
        format.json { render json: @bem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bens/1
  # PATCH/PUT /bens/1.json
  def update
    respond_to do |format|
      if @bem.update(bem_params)
        format.html { redirect_to bens_path, notice: t('messages.atualizado_sucesso', :model => "Item") }
        format.json { render :show, status: :ok, location: @bem }
      else
        format.html { render :edit }
        format.json { render json: @bem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bens/1
  # DELETE /bens/1.json
  def destroy
    @bem.destroy
    respond_to do |format|
      format.html { redirect_to bens_url, notice: t('messages.delecao_sucesso', :model => "Item") }
      format.json { head :no_content }
    end
  end

  def gera_patrimonio
    pat = Bem.gera_patrimonio
    render text: pat, layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bem
      @bem = Bem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bem_params
      params.require(:bem).permit(:grupo_insumo_id, :insumo_id, :marca, :modelo, :numero_serie, :detalhamento, :observacao, :valor, :nota_fiscal, :data_compra, :situacao_id, :estado_conservacao_id, :centro_custo_id, :setor_id, :colaborador_id, :tipo_bem_id, :qtd_disponivel, :patrimonio)
    end
end

app/helpers/bens_helper.rb
module BensHelper
end

app/views/bens/_form.html.erb
<%= form_for(bem, html: { class: 'form-horizontal' }) do |f| %>
  <%#= render 'layouts/error_messages', model_name: bem %>
  <%= render partial: 'the_notification/form', locals: { object: bem, format: :json } %>
  <div class="form-group">
    <%= f.label :tipo_bem_id, 'Tipo de Item', class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.select :tipo_bem_id, TipoBem.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
      <%=f.error_span(:tipo_bem_id) %>
    </div>
    <%= f.label :insumo_id, class: 'col-sm-1 control-label' %>
    <div class="col-sm-2">
      <%= f.select :insumo_id, Insumo.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
      <%=f.error_span(:insumo_id) %>
    </div>
  </div>
  <div class="section-patrimonio">
    <div class="form-group">
      <%= f.label :patrimonio, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.number_field :patrimonio, value: bem.patrimonio.try(:to_i), :class => 'form-control'  %>
        <%=f.error_span(:patrimonio) %>
      </div>
      <div class="col-sm-1">
        <%= button_tag 'Gerar Número', class: 'btn btn-default', id: 'btn-gera-patrimonio', type: 'button' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :marca, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.text_field :marca, :class => 'form-control'  %>
      <%=f.error_span(:marca) %>
    </div>
    <%= f.label :modelo, class: 'col-sm-1 control-label' %>
    <div class="col-sm-2">
      <%= f.text_field :modelo, :class => 'form-control'  %>
      <%=f.error_span(:modelo) %>
    </div>
  </div>
  <div class="form-group section-patrimonio">
    <%= f.label :numero_serie, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :numero_serie, :class => 'form-control'  %>
      <%=f.error_span(:numero_serie) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :detalhamento, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :detalhamento, :class => 'form-control'  %>
      <%=f.error_span(:detalhamento) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :observacao, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :observacao, :class => 'form-control'  %>
      <%=f.error_span(:observacao) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.text_field :valor, :class => 'form-control'  %>
      <%=f.error_span(:valor) %>
    </div>
    <%= f.label :nota_fiscal, class: 'col-sm-1 control-label' %>
    <div class="col-sm-2">
      <%= f.text_field :nota_fiscal, :class => 'form-control'  %>
      <%=f.error_span(:nota_fiscal) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_compra, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :data_compra, value: bem.data_compra.try(:strftime, '%d/%m/%Y'), :class => 'form-control datepicker'  %>
      <%=f.error_span(:data_compra) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :situacao_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.select :situacao_id, Situacao.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
      <%=f.error_span(:situacao_id) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :estado_conservacao_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.select :estado_conservacao_id, EstadoConservacao.to_dropdown, { include_blank: true }, {:class => 'form-control'} %>
      <%=f.error_span(:estado_conservacao_id) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :centro_custo_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.select :centro_custo_id, CentroCusto.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
      <%=f.error_span(:centro_custo_id) %>
    </div>
    <%= f.label :setor_id, class: 'col-sm-1 control-label' %>
    <div class="col-sm-2">
      <%= f.select :setor_id, Setor.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
      <%=f.error_span(:setor_id) %>
    </div>

  </div>
  <div class="form-group">
    <%= f.label :colaborador_id, 'Responsável Inicial', class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.select :colaborador_id, Colaborador.to_dropdown, { include_blank: true }, {:class => 'form-control'}  %>
      <%=f.error_span(:colaborador_id) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to I18n.t('.cancel', default: I18n.t("helpers.links.cancel")),
                  bens_path, class: 'btn' %>
    </div>
  </div>
<% end %>
<script type="text/javascript">

</script>

app/views/bens/_grid.html.erb
<%# show_filters: :when_filtered %>
<%= grid(@bens_grid) do |g|

  g.column name: 'Tipo de Item', assoc: :tipo_bem, attribute: 'descricao' do |p|
    p.tipo_bem.descricao if p.tipo_bem
  end

  g.column name: 'Grupo Insumo', assoc: :grupo_insumo, attribute: 'descricao' do |p|
    p.grupo_insumo.descricao if p.grupo_insumo
  end

  g.column name: 'Insumo', assoc: :insumo, attribute: 'descricao' do |p|
    p.insumo.descricao if p.insumo
  end

  g.column name: 'Patrimonio', attribute: 'patrimonio' do |p|
    p.patrimonio.try(:to_i)
  end
  g.column name: 'Marca', attribute: 'marca'
  g.column name: 'Modelo', attribute: 'modelo'
  g.column name: 'Nº Série', attribute: 'numero_serie'
  g.column name: 'Detalhamento', attribute: 'detalhamento'
  g.column name: 'Observação', attribute: 'observacao'
  g.column name: 'Valor', attribute: 'valor'
  g.column name: 'Nota Fiscal', attribute: 'nota_fiscal'
  g.column name: 'Data Compra', attribute: 'data_compra' do |p|
    p.data_compra.try(:strftime, '%d/%m/%Y')
  end

  g.column name: 'Situação', assoc: :situacao, attribute: 'descricao' do |p|
   p.situacao.descricao if p.situacao
  end
  g.column name: 'Estado Conserv', assoc: :estado_conservacao, attribute: 'descricao' do |p|
    p.estado_conservacao.descricao if p.estado_conservacao
  end
  g.column name: 'Centro Custo', assoc: :centro_custo, attribute: 'descricao' do |p|
   p.centro_custo.descricao if p.centro_custo
  end
  g.column name: 'Setor', assoc: :setor, attribute: 'descricao' do |p|
   p.setor.descricao if p.setor
  end

  g.column name: 'Atualizado em', attribute: 'updated_at', in_html: false do |p|
    p.updated_at.try(:strftime, '%d/%m/%Y')
  end

  g.column name: 'Cadastrado em', attribute: 'created_at', in_html: false do |p|
    p.created_at.try(:strftime, '%d/%m/%Y')
  end
  g.column html: {style: 'width: 8%;'} do |task|
     btn = link_to_show(task)
     btn << link_to_edit(edit_bem_path(task))
     btn << link_to_delete(task)
     btn
   end

end %>

app/views/bens/edit.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', :default => [:'helpers.titles.edit'], :model => 'Item') %></h3>
</div>
<%= render 'form', bem: @bem %>

app/views/bens/index.html.erb
<%- model_class = Bem -%>
<div class="page-header" style="border: none">
  <h3>Itens</h3>
  <hr/>
  <%= link_to_new new_bem_path %>
</div>
<%= render 'grid' %>

app/views/bens/new.html.erb
<div class="page-header">
  <h3><%= I18n.t('.title', default: [:'helpers.titles.new'], model: 'Item') %></h3>
</div>
<%= render 'form', bem: @bem %>

app/views/bens/show.html.erb
<div class="page-header">
  <h3>Item</h3>
</div>
<dl class="dl-horizontal">
    <dt><strong>Grupo insumo:</strong></dt>
  <dd><%= @bem.grupo_insumo.try(:descricao)  %></dd>
    <dt><strong>Insumo:</strong></dt>
  <dd><%= @bem.insumo.try(:descricao)  %></dd>
    <dt><strong>Marca:</strong></dt>
  <dd><%= @bem.marca %></dd>
    <dt><strong>Modelo:</strong></dt>
  <dd><%= @bem.modelo %></dd>
    <dt><strong>Numero serie:</strong></dt>
  <dd><%= @bem.numero_serie %></dd>
    <dt><strong>Detalhamento:</strong></dt>
  <dd><%= @bem.detalhamento %></dd>
    <dt><strong>Observacao:</strong></dt>
  <dd><%= @bem.observacao %></dd>
    <dt><strong>Valor:</strong></dt>
  <dd><%= @bem.valor %></dd>
    <dt><strong>Nota fiscal:</strong></dt>
  <dd><%= @bem.nota_fiscal %></dd>
    <dt><strong>Data compra:</strong></dt>
  <dd><%= @bem.data_compra %></dd>
    <dt><strong>Situacao:</strong></dt>
  <dd><%= @bem.situacao.try(:descricao) %></dd>
    <dt><strong>Estado conservacao:</strong></dt>
  <dd><%= @bem.estado_conservacao.try(:descricao)  %></dd>
    <dt><strong>Centro custo:</strong></dt>
  <dd><%= @bem.centro_custo.try(:descricao) %></dd>
    <dt><strong>Setor:</strong></dt>
  <dd><%= @bem.setor.try(:descricao) %></dd>
    <dt><strong>Tipo bem:</strong></dt>
  <dd><%= @bem.tipo_bem.try(:descricao) %></dd>
  </dl>
<div class="form-actions">
  <%= link_to I18n.t('.back', default: t("helpers.links.back")),
              bens_path, class: 'btn'  %>
  <%= link_to I18n.t('.edit', default: t("helpers.links.edit")),
              edit_bem_path(@bem), class: 'btn' %>
  <%= link_to I18n.t('.destroy', default: t("helpers.links.destroy")),
              bem_path(@bem),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Tem certeza que deseja remover o registro?')) },
              class: 'btn btn-danger' %>
</div>